const {SlashCommandBuilder,PermissionFlagsBits,ChannelType,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle}=require("discord.js");
const config=require("../config/server");
const {findTextChannel,findRoleByName}=require("../utils/find");
async function getOrCreateVerifiedRole(guild){let role=findRoleByName(guild,config.verifiedRoleName);if(!role)role=await guild.roles.create({name:config.verifiedRoleName,reason:"Vérification MattSlots"});return role;}
async function getOrCreateVerificationChannel(guild){let channel=findTextChannel(guild,config.channelNames.verification);if(channel)return channel;const accueil=guild.channels.cache.find(c=>c.type===ChannelType.GuildCategory&&c.name.toLowerCase().includes("accueil"));return guild.channels.create({name:"✅・vérification",type:ChannelType.GuildText,parent:accueil?.id,reason:"Création du salon de vérification"});}
module.exports={
 data:new SlashCommandBuilder().setName("verification").setDescription("Installe ou met à jour le panneau de vérification.").setDefaultMemberPermissions(PermissionFlagsBits.Administrator),
 async execute(interaction){await interaction.deferReply({ephemeral:true});const guild=interaction.guild;const verifiedRole=await getOrCreateVerifiedRole(guild);const channel=await getOrCreateVerificationChannel(guild);await channel.permissionOverwrites.edit(guild.roles.everyone,{ViewChannel:true,SendMessages:false,AddReactions:false,CreatePublicThreads:false,CreatePrivateThreads:false,SendMessagesInThreads:false});await channel.permissionOverwrites.edit(verifiedRole,{ViewChannel:false});const recent=await channel.messages.fetch({limit:50});for(const m of recent.filter(m=>m.author.id===interaction.client.user.id&&m.components.length>0).values())await m.delete().catch(()=>{});const embed=new EmbedBuilder().setColor(config.brandColor).setTitle("✅ VÉRIFICATION • MATTSLOTS").setDescription("Pour accéder au serveur, clique sur le bouton ci-dessous.\n\nEn validant, tu confirmes :\n🔞 avoir **18 ans ou plus** ;\n📜 avoir lu et accepté le règlement ;\n🤝 respecter les membres et le staff ;\n🎰 comprendre les risques liés aux jeux d'argent.").setFooter({text:"MattSlots • 18+ • Joue de manière responsable"}).setTimestamp();const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("verify:accept").setLabel("J'ai 18 ans et j'accepte").setEmoji("✅").setStyle(ButtonStyle.Success));await channel.send({embeds:[embed],components:[row]});return interaction.editReply(`✅ Vérification installée dans ${channel}.`);},
 async handleButton(interaction){await interaction.deferReply({ephemeral:true});const guild=interaction.guild;const verifiedRole=findRoleByName(guild,config.verifiedRoleName);if(!verifiedRole)return interaction.editReply("❌ Le rôle Vérifié est introuvable. Relance `/verification`.");const memberRole=guild.roles.cache.get(config.memberRoleId);if(!memberRole)return interaction.editReply("❌ Le rôle Membre est introuvable. Vérifie son ID dans `src/config/server.js`.");const member=await guild.members.fetch(interaction.user.id);const roles=[];if(!member.roles.cache.has(verifiedRole.id))roles.push(verifiedRole.id);if(!member.roles.cache.has(memberRole.id))roles.push(memberRole.id);if(!roles.length)return interaction.editReply("✅ Tu es déjà vérifié et tu possèdes déjà le rôle Membre.");await member.roles.add(roles);return interaction.editReply("✅ Vérification réussie ! Les rôles **Vérifié** et **Membre** t'ont été attribués.");}
};
