const config=require("../config/server");const store=require("../utils/store");const {brandEmbed}=require("../utils/embed");const {findTextChannel,findRoleByName}=require("../utils/find");
let twitchToken=null,twitchTokenExpiry=0;
async function twitchStatus(){const name=process.env.TWITCH_CHANNEL,clientId=process.env.TWITCH_CLIENT_ID,secret=process.env.TWITCH_CLIENT_SECRET;if(!name||!clientId||!secret)return null;if(!twitchToken||Date.now()>twitchTokenExpiry){const r=await fetch(`https://id.twitch.tv/oauth2/token?client_id=${encodeURIComponent(clientId)}&client_secret=${encodeURIComponent(secret)}&grant_type=client_credentials`,{method:"POST"});if(!r.ok)throw new Error(`Twitch token ${r.status}`);const j=await r.json();twitchToken=j.access_token;twitchTokenExpiry=Date.now()+j.expires_in*900;}const r=await fetch(`https://api.twitch.tv/helix/streams?user_login=${encodeURIComponent(name)}`,{headers:{"Client-ID":clientId,Authorization:`Bearer ${twitchToken}`}});if(!r.ok)throw new Error(`Twitch API ${r.status}`);const j=await r.json(),s=j.data?.[0];return s?{platform:"Twitch",id:s.id,title:s.title,url:`https://twitch.tv/${name}`,thumbnail:s.thumbnail_url?.replace("{width}","1280").replace("{height}","720")}:null;}
async function youtubeStatus(){const id=process.env.YOUTUBE_CHANNEL_ID;if(!id)return null;const r=await fetch(`https://www.youtube.com/feeds/videos.xml?channel_id=${encodeURIComponent(id)}`);if(!r.ok)return null;const xml=await r.text();const videoId=xml.match(/<yt:videoId>([^<]+)<\/yt:videoId>/)?.[1],title=xml.match(/<entry>[\s\S]*?<title>([^<]+)<\/title>/)?.[1];if(!videoId)return null;return{platform:"YouTube",id:videoId,title:title||"Nouvelle vidéo ou diffusion",url:`https://youtu.be/${videoId}`};}
async function kickStatus(){const name=process.env.KICK_CHANNEL;if(!name)return null;try{const r=await fetch(`https://kick.com/api/v2/channels/${encodeURIComponent(name)}`,{headers:{"User-Agent":"Mozilla/5.0"}});if(!r.ok)return null;const j=await r.json();const l=j.livestream;if(!l)return null;return{platform:"Kick",id:String(l.id),title:l.session_title||"Live MattSlots",url:`https://kick.com/${name}`,thumbnail:l.thumbnail?.url};}catch{return null;}}
async function announce(client,status){const guild=client.guilds.cache.get(process.env.GUILD_ID);if(!guild)return;const custom=store.get().settings[guild.id]?.live;const channel=custom?guild.channels.cache.get(custom):findTextChannel(guild,config.channels.live);if(!channel)return;const role=findRoleByName(guild,"🔴 Notifications Live");const e=brandEmbed(`🔴 MattSlots est en live sur ${status.platform}`,`**${status.title}**\n\n➡️ ${status.url}`);if(status.thumbnail)e.setImage(status.thumbnail);await channel.send({content:role?role.toString():undefined,embeds:[e]});}
async function check(client){for(const fn of [twitchStatus,youtubeStatus,kickStatus]){try{const s=await fn();if(!s)continue;const key=`${s.platform}:${s.id}`;if(store.get().streams[key])continue;store.update(d=>d.streams[key]={announcedAt:Date.now()});await announce(client,s);}catch(e){console.warn("⚠️ Vérification stream :",e.message);}}}
function start(client){check(client);setInterval(()=>check(client),config.streams.checkIntervalMs).unref();}
module.exports={start};
