require("dotenv").config();
const fs=require("fs"),path=require("path");
const {Client,Collection,GatewayIntentBits,Partials,REST,Routes,ActivityType,Events,MessageFlags}=require("discord.js");
const config=require("./config/server");const {startHealthServer}=require("./services/health");const giveaways=require("./services/giveaways");const streams=require("./services/streams");const {handleAutomod}=require("./services/automod");const {addXp}=require("./services/xp");
const {DISCORD_TOKEN,CLIENT_ID,GUILD_ID}=process.env;if(!DISCORD_TOKEN||!CLIENT_ID||!GUILD_ID){console.error("❌ Variables manquantes : DISCORD_TOKEN, CLIENT_ID ou GUILD_ID.");process.exit(1);}
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent],partials:[Partials.Channel]});client.commands=new Collection();
for(const file of fs.readdirSync(path.join(__dirname,"commands")).filter(f=>f.endsWith(".js"))){const c=require(path.join(__dirname,"commands",file));if(c?.data&&c?.execute)client.commands.set(c.data.name,c);}
client.once(Events.ClientReady,async()=>{console.log(`✅ Connecté en tant que ${client.user.tag}`);client.user.setPresence({activities:[{name:"la communauté MattSlots 🎰",type:ActivityType.Watching}],status:"online"});const rest=new REST({version:"10"}).setToken(DISCORD_TOKEN);await rest.put(Routes.applicationGuildCommands(CLIENT_ID,GUILD_ID),{body:client.commands.map(c=>c.data.toJSON())});console.log(`✅ ${client.commands.size} commandes slash enregistrées.`);giveaways.restore(client);streams.start(client);});
client.on(Events.InteractionCreate,async i=>{try{if(i.isChatInputCommand()){const c=client.commands.get(i.commandName);if(c)await c.execute(i);return;}if(!i.isButton())return;if(i.customId==="verify:accept")return client.commands.get("verification").button(i);if(i.customId.startsWith("selfrole:"))return client.commands.get("roles").button(i);if(i.customId.startsWith("ticket:"))return client.commands.get("tickets").button(i);if(i.customId.startsWith("giveaway:join:"))return giveaways.join(i);}catch(e){console.error("❌ Erreur interaction :",e);const p={content:"❌ Une erreur est survenue. Consulte les logs Render.",flags:MessageFlags.Ephemeral};if(i.deferred||i.replied)await i.followUp(p).catch(()=>{});else await i.reply(p).catch(()=>{});}});
client.on(Events.MessageCreate,async m=>{try{if(await handleAutomod(m))return;const r=addXp(m);if(r?.leveledUp)await m.channel.send(`🎉 ${m.author}, tu passes au **niveau ${r.level}** !`).catch(()=>{});}catch(e){console.error("❌ Erreur message :",e);}});
client.on(Events.Error,e=>console.error("❌ Erreur Discord :",e));process.on("unhandledRejection",e=>console.error("❌ Promesse non gérée :",e));process.on("uncaughtException",e=>console.error("❌ Exception non gérée :",e));
startHealthServer(client);client.login(DISCORD_TOKEN);
